version: '3.4'

services:

  backend-server:
    container_name: a-real-backend
    build: 
      context: ./services/backend/
      dockerfile: Dockerfile
    command: ./app
    ports:
      - 8091:8091
  duelfrontend:
    build: 
      context: ./services/frontend
      dockerfile: Dockerfile.prod
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: a-real-frontend