version: '3.4'

services:

  backend-server:
    container_name: "a-real-backend"
    build: 
      context: ./services/backend/
      dockerfile: Dockerfile
    command: ./app
    ports:
      - 8091:8091
